version: '3'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: parser
      MYSQL_USER: parser_user
      MYSQL_PASSWORD: parser
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - lamp-docker

  www:
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/Php.Dockerfile
    volumes:
      - "../src/:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
  

networks:
  lamp-docker:
    driver: bridge